package com.gangulwar.natguesser.utils

fun getCountryNameById(countryCode: String): String {
    val countryMap = mapOf(
        "AF" to "Afghanistan",
        "AL" to "Albania",
        "DZ" to "Algeria",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AU" to "Australia",
        "AT" to "Austria",
        "AZ" to "Azerbaijan",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BY" to "Belarus",
        "BE" to "Belgium",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BT" to "Bhutan",
        "BO" to "Bolivia",
        "BA" to "Bosnia and Herzegovina",
        "BW" to "Botswana",
        "BR" to "Brazil",
        "BG" to "Bulgaria",
        "BF" to "Burkina Faso",
        "BI" to "Burundi",
        "KH" to "Cambodia",
        "CM" to "Cameroon",
        "CA" to "Canada",
        "CF" to "Central African Republic",
        "TD" to "Chad",
        "CI" to "Côte d’Ivoire",
        "CL" to "Chile",
        "CN" to "China",
        "CO" to "Colombia",
        "CG" to "Congo",
        "CR" to "Costa Rica",
        "HR" to "Croatia",
        "CU" to "Cuba",
        "CY" to "Cyprus",
        "CZ" to "Czechia",
        "DK" to "Denmark",
        "DJ" to "Djibouti",
        "DO" to "Dominican Republic",
        "EC" to "Ecuador",
        "EG" to "Egypt",
        "SV" to "El Salvador",
        "EE" to "Estonia",
        "ET" to "Ethiopia",
        "FI" to "Finland",
        "FR" to "France",
        "GA" to "Gabon",
        "GE" to "Georgia",
        "DE" to "Germany",
        "GH" to "Ghana",
        "GR" to "Greece",
        "GT" to "Guatemala",
        "HN" to "Honduras",
        "HK" to "Hong Kong",
        "HU" to "Hungary",
        "IS" to "Iceland",
        "IN" to "India",
        "ID" to "Indonesia",
        "IR" to "Iran",
        "IQ" to "Iraq",
        "IE" to "Ireland",
        "IL" to "Israel",
        "IT" to "Italy",
        "JM" to "Jamaica",
        "JP" to "Japan",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KE" to "Kenya",
        "KW" to "Kuwait",
        "KG" to "Kyrgyzstan",
        "LA" to "Laos",
        "LV" to "Latvia",
        "LB" to "Lebanon",
        "LY" to "Libya",
        "LT" to "Lithuania",
        "LU" to "Luxembourg",
        "MG" to "Madagascar",
        "MY" to "Malaysia",
        "MV" to "Maldives",
        "ML" to "Mali",
        "MT" to "Malta",
        "MX" to "Mexico",
        "MD" to "Moldova",
        "MN" to "Mongolia",
        "ME" to "Montenegro",
        "MA" to "Morocco",
        "MZ" to "Mozambique",
        "MM" to "Myanmar",
        "NA" to "Namibia",
        "NP" to "Nepal",
        "NL" to "Netherlands",
        "NZ" to "New Zealand",
        "NI" to "Nicaragua",
        "NE" to "Niger",
        "NG" to "Nigeria",
        "NO" to "Norway",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PS" to "Palestine",
        "PA" to "Panama",
        "PG" to "Papua New Guinea",
        "PY" to "Paraguay",
        "PE" to "Peru",
        "PH" to "Philippines",
        "PL" to "Poland",
        "PT" to "Portugal",
        "QA" to "Qatar",
        "RO" to "Romania",
        "RU" to "Russia",
        "RW" to "Rwanda",
        "SA" to "Saudi Arabia",
        "SN" to "Senegal",
        "RS" to "Serbia",
        "SG" to "Singapore",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "ZA" to "South Africa",
        "KR" to "South Korea",
        "ES" to "Spain",
        "LK" to "Sri Lanka",
        "SD" to "Sudan",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "SY" to "Syria",
        "TW" to "Taiwan",
        "TZ" to "Tanzania",
        "TH" to "Thailand",
        "TN" to "Tunisia",
        "TR" to "Türkiye",
        "TM" to "Turkmenistan",
        "UG" to "Uganda",
        "UA" to "Ukraine",
        "AE" to "United Arab Emirates",
        "GB" to "United Kingdom",
        "US" to "United States",
        "UY" to "Uruguay",
        "UZ" to "Uzbekistan",
        "VE" to "Venezuela",
        "VN" to "Vietnam",
        "YE" to "Yemen",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe"
    )

    return countryMap[countryCode.uppercase()] ?: "Unknown Country"
}